AllCops:
  TargetRubyVersion: 3.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/ConditionalAssignment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Enabled: true
  Max: 20

Documentation:
  Enabled: false
