AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - Gemfile
    - "*.md"
    - "*.text"
    - utanone.gemspec
    - "bin/*"
    - Rakefile
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/ConditionalAssignment:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Enabled: true
  Max: 20

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 8

Metrics/AbcSize:
  Enabled: true
  Max: 20

Metrics/BlockLength:
  Enabled: false

Documentation:
  Enabled: false
